# Generated by Django 5.0.2 on 2024-02-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_brand_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('comment', models.TextField(blank=True)),
                ('star', models.IntegerField(default=1)),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
