# Generated by Django 5.0.2 on 2024-03-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='slug',
            field=models.CharField(max_length=200),
        ),
    ]
